pipeline {
    agent {
        docker {
            image 'node:18'  // This means Jenkins will run inside a Node.js 18 container
        }
    }

    environment {
        IMAGE_NAME = 'aditiijan46/hello-world-node'
        DOCKER_CREDENTIALS_ID = 'docker-hub-creds'
    }

    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/aditiijan46/CI-CD-pipeline-projects.git'
            }
        }

        stage('Build') {
            steps {
                sh 'npm install'
            }
        }

        stage('Docker Build') {
            steps {
                sh "docker build -t ${IMAGE_NAME} ."
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: "${DOCKER_CREDENTIALS_ID}",
                    usernameVariable: 'aditiijan46',
                    passwordVariable: 'shubhamaditi'
                )]) {
                    sh """
                        echo "${PASSWORD}" | docker login -u "${USERNAME}" --password-stdin
                        docker push ${IMAGE_NAME}
                    """
                }
            }
        }
    }
}
