pipeline {
    agent any
    environment {
        IMAGE_NAME = 'aditiijan46/hello-world-nod'
        DOCKER_CREDENTIALS_ID = 'docker-hub-creds'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/aditiijan46/CI-CD-pipeline-projects.git'
            }
        }

        stage('Build') {
            steps {
                sh 'cd Practice-pipeline-project && npm install'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $IMAGE_NAME Practice-pipeline-project/'
            }
        }
        stage('Docker Push') {
    steps {
        withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
            sh """
                echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                docker push aditiijan46/hello-world-nod:latest
            """
        }
    }
}


        /*stage('Docker Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: "${DOCKER_CREDENTIALS_ID}",
                    usernameVariable: 'aditiijan46',
                    passwordVariable: 'shubhamaditi'
                )]) {
                    sh """
                        echo $PASSWORD | docker login -u $USERNAME --password-stdin
                        docker push $IMAGE_NAME
                    """
                }
            }
        }*/
    }
}
